CREATE TYPE "public"."role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "dashboard_snapshots" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"date" date NOT NULL,
	"net_worth_cny" numeric(15, 2) NOT NULL,
	"net_worth_usd" numeric(15, 2) NOT NULL,
	"high_water_mark" numeric(15, 2) NOT NULL,
	"drawdown_amount" numeric(15, 2),
	"drawdown_percent" numeric(10, 4),
	"daily_pnl" numeric(15, 2),
	"daily_pnl_percent" numeric(10, 4),
	"cash_usd" numeric(15, 2) DEFAULT '0',
	"cash_hkd" numeric(15, 2) DEFAULT '0',
	"cash_cny" numeric(15, 2) DEFAULT '0',
	"cash_total_cny" numeric(15, 2) DEFAULT '0',
	"long_ratio" numeric(5, 2),
	"short_ratio" numeric(5, 2),
	"cash_ratio" numeric(5, 2),
	"long_value_cny" numeric(15, 2),
	"short_value_cny" numeric(15, 2),
	"usd_cny_rate" numeric(10, 4),
	"hkd_cny_rate" numeric(10, 4),
	"total_positions" integer DEFAULT 0,
	"winning_positions" integer DEFAULT 0,
	"losing_positions" integer DEFAULT 0,
	"data_source" varchar(20) DEFAULT 'IBKR',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "dashboard_snapshots_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "option_positions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"snapshot_date" date NOT NULL,
	"symbol" varchar(50) NOT NULL,
	"underlying_ticker" varchar(20),
	"underlying_name" varchar(255),
	"option_type" varchar(10),
	"strike_price" numeric(15, 4),
	"expiry_date" date,
	"multiplier" integer DEFAULT 100,
	"market" varchar(10),
	"currency" varchar(3),
	"quantity" integer NOT NULL,
	"avg_cost" numeric(15, 4),
	"current_price" numeric(15, 4),
	"market_value" numeric(15, 2),
	"unrealized_pnl" numeric(15, 2),
	"unrealized_pnl_percent" numeric(10, 4),
	"market_value_cny" numeric(15, 2),
	"unrealized_pnl_cny" numeric(15, 2),
	"delta" numeric(10, 4),
	"gamma" numeric(10, 4),
	"theta" numeric(10, 4),
	"vega" numeric(10, 4),
	"implied_volatility" numeric(10, 4),
	"weight_percent" numeric(5, 2),
	"days_to_expiry" integer,
	"in_the_money" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "risk_metrics" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"date" date NOT NULL,
	"var_1day_95" numeric(10, 4),
	"var_1day_99" numeric(10, 4),
	"var_10day_95" numeric(10, 4),
	"current_drawdown_percent" numeric(10, 4),
	"max_drawdown_percent" numeric(10, 4),
	"max_drawdown_duration_days" integer,
	"annualized_return" numeric(10, 4),
	"annualized_volatility" numeric(10, 4),
	"sharpe_ratio" numeric(10, 4),
	"sortino_ratio" numeric(10, 4),
	"calmar_ratio" numeric(10, 4),
	"win_rate" numeric(10, 4),
	"profit_factor" numeric(10, 4),
	"avg_win" numeric(15, 2),
	"avg_loss" numeric(15, 2),
	"market_beta" numeric(10, 4),
	"correlation_sp500" numeric(10, 4),
	"top_position_concentration" numeric(10, 4),
	"top5_concentration" numeric(10, 4),
	"herfindahl_index" numeric(10, 4),
	"calculation_period_days" integer DEFAULT 365,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "risk_metrics_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "stock_positions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"snapshot_date" date NOT NULL,
	"ticker" varchar(20) NOT NULL,
	"name" varchar(255),
	"market" varchar(10),
	"currency" varchar(3),
	"quantity" integer NOT NULL,
	"avg_cost" numeric(15, 4),
	"current_price" numeric(15, 4),
	"market_value" numeric(15, 2),
	"unrealized_pnl" numeric(15, 2),
	"unrealized_pnl_percent" numeric(10, 4),
	"market_value_cny" numeric(15, 2),
	"unrealized_pnl_cny" numeric(15, 2),
	"position_type" varchar(10),
	"weight_percent" numeric(5, 2),
	"stop_loss_price" numeric(15, 4),
	"stop_loss_triggered" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"date" date NOT NULL,
	"ticker" varchar(20) NOT NULL,
	"name" varchar(255),
	"market" varchar(2),
	"currency" varchar(3),
	"action" varchar(20) NOT NULL,
	"price" numeric(15, 4),
	"quantity" integer DEFAULT 0 NOT NULL,
	"amount" numeric(15, 2),
	"amount_cny" numeric(15, 2),
	"fee" numeric(15, 2) DEFAULT '0',
	"strategy_note" text,
	"is_planned" boolean DEFAULT false,
	"watchlist_days" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"risk_limits" jsonb DEFAULT '{"stopLossPercent":-20,"maxDrawdownPercent":5,"positionLimitPercent":15,"watchlistCooldownDays":7,"positionLimitExceptions":[]}'::jsonb,
	"ibkr_last_refresh" timestamp with time zone,
	"ibkr_sync_enabled" boolean DEFAULT true,
	"panic_lockdown" jsonb,
	"default_currency" varchar(3) DEFAULT 'CNY',
	"theme" varchar(20) DEFAULT 'light',
	"sidebar_width" integer DEFAULT 280,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "user_settings_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE TABLE "watchlist" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticker" varchar(20) NOT NULL,
	"name" varchar(255),
	"market" varchar(2),
	"currency" varchar(3),
	"added_date" date DEFAULT now() NOT NULL,
	"target_price" numeric(15, 4),
	"notes" text,
	"current_price" numeric(15, 4),
	"change_percent" numeric(10, 4),
	"last_price_update" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "watchlist_ticker_unique" UNIQUE("ticker")
);
